# Markdownlint configuration

# Enable all default rules, then override as needed.
default: true

# Blank line inside lists is allowed.
MD032: false

# No blank lines around headings allowed.
MD022: false

# Line length is enforced at 80 columns, excluding code blocks and tables.
MD013:
  line_length: 80
  code_blocks: false
  tables: false
